# Generated by Django 4.1.7 on 2023-04-25 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=20)),
                ('celular', models.CharField(max_length=10)),
                ('documento', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('codigo', models.CharField(max_length=1)),
                ('tipo', models.CharField(max_length=20)),
                ('precio', models.CharField(max_length=20)),
                ('marca', models.CharField(max_length=20)),
            ],
        ),
    ]
